# Cloudflare Pages Configuration
# This file is automatically read by Cloudflare Pages

# Build configuration
[build]
  command = "npm run build"
  publish = ".next"

# Environment variables
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com https://challenges.cloudflare.com; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://cloudflareinsights.com https://*.cloudflare.com; frame-src 'self' https://challenges.cloudflare.com; worker-src 'self' blob:"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/sun7piscine-photos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects (if needed)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301
